# Generated by Django 4.1 on 2022-08-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sayfa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=50, unique=True)),
                ('fotograf', models.ImageField(null=True, upload_to='')),
                ('baslik', models.CharField(max_length=100)),
                ('yazi', models.TextField(max_length=1000)),
                ('arkaplan', models.ImageField(null=True, upload_to='')),
                ('logo', models.ImageField(null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Sayfalar',
            },
        ),
    ]
