# Generated by Django 4.1 on 2022-08-25 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_sayfa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sayfa',
            name='baslik',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sayfa',
            name='yazi',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
