# Generated by Django 4.1 on 2022-08-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_sayfa_baslik_alter_sayfa_yazi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sayfa',
            name='fotograf',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
