# Generated by Django 4.1 on 2022-08-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_user_options_alter_sayfa_arkaplan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaleriFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotograf', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Galeri Fotoğrafları',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Menü',
            },
        ),
    ]
