# Generated by Django 4.1 on 2022-08-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_menu_isim'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailAdresi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adres', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Mail Adresi',
            },
        ),
    ]
